import { test, describe, before, after } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { execSync } from "node:child_process";
import { runInit } from "../src/commands/init.js";
import { runDoctor } from "../src/commands/doctor.js";
import { runTraceCommand } from "../src/commands/trace.js";
import { runBuild } from "../src/commands/build.js";
import { runTestCommand } from "../src/commands/test.js";
import { runInspect } from "../src/commands/inspect.js";
import { runDiffCommand } from "../src/commands/diff.js";
import { runCiCommand } from "../src/commands/ci.js";
import { runHomebrewCommand } from "../src/commands/homebrew.js";
import { runReleaseCommand } from "../src/commands/release.js";

describe("End-to-End SEA Toolchain", () => {
  const tmpProject = path.join(os.tmpdir(), `yekpare-e2e-${Date.now()}`);
  let buildResult: any;
  let originalLog: typeof console.log;

  before(() => {
    originalLog = console.log;
    console.log = () => {};
  });

  after(() => {
    console.log = originalLog;
    try {
      fs.rmSync(tmpProject, { recursive: true, force: true });
    } catch {}
  });

  test("1. project setup and init: scaffolds config and discovers project entry", async () => {
    fs.mkdirSync(tmpProject, { recursive: true });
    fs.mkdirSync(path.join(tmpProject, "src"), { recursive: true });
    fs.mkdirSync(path.join(tmpProject, "templates"), { recursive: true });
    fs.mkdirSync(path.join(tmpProject, "data"), { recursive: true });

    // Setup sample project files
    const samplePackageJson = {
      name: "sample-cli",
      version: "1.0.0",
      type: "module",
      bin: {
        "sample-cli": "./src/cli.ts",
      },
      engines: {
        node: ">=20.0.0",
      },
    };
    fs.writeFileSync(
      path.join(tmpProject, "package.json"),
      JSON.stringify(samplePackageJson, null, 2)
    );

    fs.writeFileSync(
      path.join(tmpProject, "templates", "hello.txt"),
      "Hello {{name}}, welcome to Yekpare SEA standalone binaries!\n"
    );

    fs.writeFileSync(
      path.join(tmpProject, "data", "config.json"),
      JSON.stringify({ mode: "production", features: ["sea", "assets"], count: 42 })
    );

    const sampleCliTs = `
      import { asset, isSea } from "yekpare/runtime";

      const args = process.argv.slice(2);

      if (args.includes("--version")) {
        console.log("1.0.0");
        process.exit(0);
      }

      if (args.includes("--help")) {
        console.log("sample-cli - A demonstration standalone executable");
        process.exit(0);
      }

      if (args.includes("--test-assets")) {
        if (!asset.exists("templates/hello.txt")) {
          throw new Error("Missing templates/hello.txt");
        }
        const text = asset.text("templates/hello.txt");
        if (!text.includes("Hello")) {
          throw new Error("Corrupt templates/hello.txt content");
        }
        if (!asset.exists("data/config.json")) {
          throw new Error("Missing data/config.json");
        }
        const json = asset.json("data/config.json");
        if (json.mode !== "production" || json.count !== 42) {
          throw new Error("Corrupt data/config.json content: " + JSON.stringify(json));
        }
        const buf = asset.buffer("templates/hello.txt");
        if (!Buffer.isBuffer(buf) || buf.length === 0) {
          throw new Error("Invalid buffer");
        }
        const keys = asset.keys();
        if (!keys.includes("templates/hello.txt") || !keys.includes("data/config.json")) {
          throw new Error("Missing keys in asset.keys(): " + keys.join(","));
        }
        if (asset.exists("nonexistent.txt")) {
          throw new Error("nonexistent file returned true");
        }
        console.log("ASSETS_VERIFIED_OK");
        process.exit(0);
      }

      const nameArgIdx = args.indexOf("--name");
      const name = nameArgIdx !== -1 ? args[nameArgIdx + 1] : "World";

      let template = "Hello, {{name}}!";
      if (asset.exists("templates/hello.txt")) {
        template = asset.text("templates/hello.txt");
      }

      console.log(template.replace("{{name}}", name).trim());
    `;
    fs.writeFileSync(path.join(tmpProject, "src", "cli.ts"), sampleCliTs);

    // Run init to scaffold config
    await runInit({ cwd: tmpProject });
    const configPath = path.join(tmpProject, "yekpare.config.ts");
    assert.ok(fs.existsSync(configPath), "yekpare.config.ts should be generated by init");

    // Augment config with asset globs
    const configCode = `
      import { defineConfig } from "yekpare";

      export default defineConfig({
        entry: "./src/cli.ts",
        name: "sample-cli",
        version: "1.0.0",
        assets: [
          "./templates/**/*",
          "./data/**/*",
        ],
        bundle: {
          minify: false,
        },
      });
    `;
    fs.writeFileSync(configPath, configCode);
  });

  test("2. doctor: performs static analysis and asset inventory", async () => {
    const doctorResult = await runDoctor({
      cwd: tmpProject,
      json: true,
    });
    assert.equal(doctorResult.project.format, "ESM");
    assert.equal(doctorResult.result, "SEA compatible");
    assert.equal(doctorResult.compatibility.dynamicRequireWarnings, 0);
    assert.equal(doctorResult.compatibility.nativeAddonsDetected, 0);
    assert.equal(doctorResult.assets.explicit, 2);
  });

  test("3. trace: traces execution of node command", async () => {
    const traceResult = await runTraceCommand({
      commandArgs: [process.execPath, "-e", "console.log('yekpare-trace-ok')"],
      cwd: tmpProject,
      json: true,
    });
    assert.equal(traceResult.exitCode, 0);
    assert.ok(Array.isArray(traceResult.loadedModules));
  });

  test("4. build: compiles standalone Node SEA executable with assets and stripping", async () => {
    buildResult = await runBuild({
      cwd: tmpProject,
      strip: true,
      quiet: true,
      json: true,
    });
    assert.ok(buildResult.outputPath);
    assert.ok(fs.existsSync(buildResult.outputPath));
    assert.ok(buildResult.executableSize > 1000000, "Executable must be > 1MB");
    assert.equal(buildResult.manifest.application.name, "sample-cli");
    assert.equal(buildResult.manifest.assets.length, 2);
  });

  test("5. binary execution: validates CLI flags and standard output", () => {
    // Test --version
    const versionOutput = execSync(`"${buildResult.outputPath}" --version`, {
      encoding: "utf8",
    }).trim();
    assert.equal(versionOutput, "1.0.0");

    // Test --help
    const helpOutput = execSync(`"${buildResult.outputPath}" --help`, {
      encoding: "utf8",
    }).trim();
    assert.match(helpOutput, /sample-cli/);

    // Test custom arguments
    const customRunOutput = execSync(
      `"${buildResult.outputPath}" --name Antigravity`,
      { encoding: "utf8" }
    ).trim();
    assert.equal(
      customRunOutput,
      "Hello Antigravity, welcome to Yekpare SEA standalone binaries!"
    );
  });

  test("6. runtime asset API: executes asset.text, json, buffer, keys inside standalone binary", () => {
    const assetCheckOutput = execSync(
      `"${buildResult.outputPath}" --test-assets`,
      { encoding: "utf8" }
    ).trim();
    assert.equal(assetCheckOutput, "ASSETS_VERIFIED_OK");
  });

  test("7. test command: verifies binary integrity and auto-discovery", async () => {
    // Test with explicit binary path
    const passedExplicit = await runTestCommand({
      binaryPath: buildResult.outputPath,
      cwd: tmpProject,
    });
    assert.equal(passedExplicit, true);

    // Test auto-discovery from dist/
    const passedAuto = await runTestCommand({
      cwd: tmpProject,
    });
    assert.equal(passedAuto, true);
  });

  test("8. inspect: extracts and verifies embedded SEA manifest", async () => {
    const inspectResult = await runInspect({
      binaryPath: buildResult.outputPath,
      json: true,
    });
    assert.equal(inspectResult.executable.name, "sample-cli");
    assert.ok(inspectResult.manifest);
    assert.equal(inspectResult.manifest.application.name, "sample-cli");
    assert.equal(inspectResult.contents.assetsCount, 2);
  });

  test("9. diff: compares binary against itself and reports zero drift", async () => {
    const diffResult = await runDiffCommand({
      bin1: buildResult.outputPath,
      bin2: buildResult.outputPath,
      json: true,
    });
    assert.equal(diffResult.sizeDiff, 0);
    assert.equal(diffResult.bundleDiff, 0);
    assert.equal(diffResult.file1.manifest.application.name, "sample-cli");
    assert.equal(diffResult.file2.manifest.application.name, "sample-cli");
  });

  test("10. distribution: generates multi-platform CI release workflow", async () => {
    await runCiCommand({ cwd: tmpProject });
    const workflowPath = path.join(
      tmpProject,
      ".github",
      "workflows",
      "yekpare-release.yml"
    );
    assert.ok(fs.existsSync(workflowPath));
    const content = fs.readFileSync(workflowPath, "utf8");
    assert.match(content, /matrix:/);
    assert.match(content, /macos-14/);
    assert.match(content, /ubuntu-latest/);
  });

  test("11. distribution: generates Homebrew tap formula", async () => {
    await runHomebrewCommand({
      cwd: tmpProject,
      repo: "https://github.com/litepacks/sample-cli",
    });
    const formulaPath = path.join(tmpProject, "Formula", "sample-cli.rb");
    assert.ok(fs.existsSync(formulaPath));
    const content = fs.readFileSync(formulaPath, "utf8");
    assert.match(content, /class SampleCli < Formula/);
    assert.match(content, /litepacks\/sample-cli/);
  });

  test("12. distribution: packages release tarballs with checksums", async () => {
    await runReleaseCommand({ cwd: tmpProject });
    const checksumsPath = path.join(
      tmpProject,
      "dist",
      "release",
      "checksums.txt"
    );
    assert.ok(fs.existsSync(checksumsPath));
    const checksums = fs.readFileSync(checksumsPath, "utf8");
    assert.match(checksums, /sample-cli/);
  });

  test("13. distribution: verifies Linux Debian (.deb) staging directory & control file", () => {
    const pkgName = "sample-cli";
    const pkgVersion = "1.0.0";
    const arch = "amd64";
    const stageDir = path.join(tmpProject, `${pkgName}_${pkgVersion}_${arch}`);

    // Create hierarchy
    fs.mkdirSync(path.join(stageDir, "DEBIAN"), { recursive: true });
    fs.mkdirSync(path.join(stageDir, "usr", "local", "bin"), { recursive: true });

    // Copy binary
    const destBin = path.join(stageDir, "usr", "local", "bin", pkgName);
    fs.copyFileSync(buildResult.outputPath, destBin);
    fs.chmodSync(destBin, 0o755);

    // Create control file
    const controlContent = [
      `Package: ${pkgName}`,
      `Version: ${pkgVersion}`,
      `Section: utils`,
      `Priority: optional`,
      `Architecture: ${arch}`,
      `Maintainer: litepacks <hello@litepacks.dev>`,
      `Description: Standalone CLI application built with Yekpare`,
      "",
    ].join("\n");
    fs.writeFileSync(path.join(stageDir, "DEBIAN", "control"), controlContent);

    // Verify structure
    assert.ok(fs.existsSync(path.join(stageDir, "DEBIAN", "control")));
    assert.ok(fs.existsSync(destBin));
    const stat = fs.statSync(destBin);
    if (process.platform !== "win32") {
      assert.equal(stat.mode & 0o111, 0o111, "Binary in .deb package must be executable");
    }
    const readControl = fs.readFileSync(path.join(stageDir, "DEBIAN", "control"), "utf8");
    assert.match(readControl, /Package: sample-cli/);
    assert.match(readControl, /Maintainer: litepacks/);
  });
});
