import fs from "node:fs";
import path from "node:path";
import pc from "picocolors";
import { formatHeader, symbols } from "../utils/format.js";
import { ensureDir } from "../utils/fs.js";
import { resolveConfig } from "../config/index.js";

export interface InstallerCliOptions {
  repo?: string;
  output?: string;
  defaultDir?: string;
  cwd?: string;
}

export function generateInstallScript(options: {
  appName: string;
  repo?: string;
  defaultDir?: string;
}): string {
  const appName = options.appName;
  let rawRepo = options.repo || `username/${appName}`;
  // Extract owner/repo from GitHub URL if full URL is passed
  rawRepo = rawRepo
    .replace(/^https?:\/\/github\.com\//, "")
    .replace(/\.git$/, "")
    .replace(/\/+$/, "");

  const defaultDir = options.defaultDir || "/usr/local/bin";

  return `#!/usr/bin/env bash
# ==============================================================================
# ${appName} Standalone Installer Script (macOS & Linux)
# Generated by Yekpare (https://github.com/litepacks/yekpare)
# ==============================================================================

set -euo pipefail

APP_NAME="${appName}"
DEFAULT_REPO="${rawRepo}"
REPO="\${GITHUB_REPO:-\${REPO:-\$DEFAULT_REPO}}"
DEFAULT_INSTALL_DIR="${defaultDir}"
INSTALL_DIR="\${INSTALL_DIR:-\$DEFAULT_INSTALL_DIR}"
VERSION="\${VERSION:-latest}"

# Color codes (only when output is a terminal)
if [ -t 1 ]; then
  RED='\\033[0;31m'
  GREEN='\\033[0;32m'
  CYAN='\\033[0;36m'
  YELLOW='\\033[1;33m'
  DIM='\\033[2m'
  BOLD='\\033[1m'
  NC='\\033[0m' # No Color
else
  RED=''
  GREEN=''
  CYAN=''
  YELLOW=''
  DIM=''
  BOLD=''
  NC=''
fi

info() {
  printf "  \${CYAN}•\${NC} %s\\n" "$1"
}

success() {
  printf "  \${GREEN}✓\${NC} %s\\n" "$1"
}

warn() {
  printf "  \${YELLOW}! %s\${NC}\\n" "$1"
}

error() {
  printf "  \${RED}✗ Error:\${NC} %s\\n" "$1" >&2
  exit 1
}

# Parse optional arguments: --dir <path>, --version <v>, --help
while [[ $# -gt 0 ]]; do
  case "$1" in
    -b|--dir|--to)
      INSTALL_DIR="$2"
      shift 2
      ;;
    -v|--version)
      VERSION="$2"
      shift 2
      ;;
    -r|--repo)
      REPO="$2"
      shift 2
      ;;
    -h|--help)
      echo "Usage: install.sh [options]"
      echo ""
      echo "Options:"
      echo "  -b, --dir <path>     Installation directory (default: \${DEFAULT_INSTALL_DIR})"
      echo "  -v, --version <tag>  Specific release version (default: latest)"
      echo "  -r, --repo <repo>    GitHub repository (owner/repo)"
      echo "  -h, --help           Show this help message"
      exit 0
      ;;
    *)
      warn "Unknown option: $1"
      shift
      ;;
  esac
done

printf "\\n\${BOLD}\${CYAN}  Installing \${APP_NAME}\${NC}\\n\\n"

# 1. Detect Operating System
OS="$(uname -s)"
case "$OS" in
  Darwin)
    PLATFORM="darwin"
    ;;
  Linux)
    PLATFORM="linux"
    ;;
  *)
    error "Unsupported operating system: $OS. This script supports macOS (Darwin) and Linux."
    ;;
esac

# 2. Detect Architecture
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64|amd64)
    TARGET_ARCH="x64"
    ;;
  arm64|aarch64)
    TARGET_ARCH="arm64"
    ;;
  *)
    error "Unsupported CPU architecture: $ARCH."
    ;;
esac

TARGET="\${PLATFORM}-\${TARGET_ARCH}"
info "Detected platform: \${BOLD}\${TARGET}\${NC}"

# 3. Check for curl or wget
if command -v curl >/dev/null 2>&1; then
  HTTP_CLIENT="curl"
elif command -v wget >/dev/null 2>&1; then
  HTTP_CLIENT="wget"
else
  error "Neither curl nor wget was found. Please install curl or wget to continue."
fi

download_file() {
  local url="$1"
  local dest="$2"
  if [ "$HTTP_CLIENT" = "curl" ]; then
    curl -fsSL --retry 3 "$url" -o "$dest"
  else
    wget -qO "$dest" "$url"
  fi
}

# 4. Resolve download URL
ARCHIVE_NAME="\${APP_NAME}-\${TARGET}.tar.gz"

if [ "$VERSION" = "latest" ]; then
  DOWNLOAD_URL="https://github.com/\${REPO}/releases/latest/download/\${ARCHIVE_NAME}"
else
  # Ensure version starts with 'v' if omitted
  TAG="$VERSION"
  if [[ ! "$TAG" =~ ^v ]]; then
    TAG="v\${VERSION}"
  fi
  DOWNLOAD_URL="https://github.com/\${REPO}/releases/download/\${TAG}/\${ARCHIVE_NAME}"
fi

info "Downloading \${BOLD}\${ARCHIVE_NAME}\${NC} from \${DIM}\${REPO}\${NC}..."

# 5. Create temporary working directory
TMP_DIR="$(mktemp -d -t "\${APP_NAME}-install-XXXXXX")"
trap 'rm -rf "$TMP_DIR"' EXIT INT TERM

ARCHIVE_PATH="\${TMP_DIR}/\${ARCHIVE_NAME}"

if ! download_file "$DOWNLOAD_URL" "$ARCHIVE_PATH"; then
  error "Failed to download release archive from:\\n    \$DOWNLOAD_URL\\n  Please verify the repository '\$REPO' and release version '\$VERSION'."
fi

# 6. Extract archive
tar -xzf "$ARCHIVE_PATH" -C "$TMP_DIR"

EXTRACTED_BIN="\${TMP_DIR}/\${APP_NAME}"
if [ ! -f "$EXTRACTED_BIN" ]; then
  # Search for the binary in subdirectories if archive had nested folder
  FOUND_BIN="$(find "$TMP_DIR" -type f -name "$APP_NAME" | head -n 1)"
  if [ -n "$FOUND_BIN" ]; then
    EXTRACTED_BIN="$FOUND_BIN"
  else
    error "Executable '\$APP_NAME' not found in downloaded archive."
  fi
fi

# 7. Prepare installation directory
# If default dir is not writable without sudo, fallback to ~/.local/bin if needed
TARGET_BIN="\${INSTALL_DIR}/\${APP_NAME}"

if [ ! -d "$INSTALL_DIR" ]; then
  if mkdir -p "$INSTALL_DIR" 2>/dev/null; then
    :
  else
    if [ "$INSTALL_DIR" = "$DEFAULT_INSTALL_DIR" ] && [ "$(id -u)" -ne 0 ]; then
      INSTALL_DIR="$HOME/.local/bin"
      TARGET_BIN="\${INSTALL_DIR}/\${APP_NAME}"
      mkdir -p "$INSTALL_DIR"
      warn "Cannot write to \${DEFAULT_INSTALL_DIR}, installing to \${INSTALL_DIR}"
    else
      error "Cannot create directory '\$INSTALL_DIR'. Try running with sudo or specifying --dir."
    fi
  fi
fi

if [ ! -w "$INSTALL_DIR" ]; then
  if [ "$INSTALL_DIR" = "$DEFAULT_INSTALL_DIR" ] && [ "$(id -u)" -ne 0 ]; then
    INSTALL_DIR="$HOME/.local/bin"
    TARGET_BIN="\${INSTALL_DIR}/\${APP_NAME}"
    mkdir -p "$INSTALL_DIR"
    warn "Cannot write to \${DEFAULT_INSTALL_DIR}, installing to \${INSTALL_DIR}"
  else
    error "Permission denied: Cannot write to '\$INSTALL_DIR'. Run with sudo or pass --dir."
  fi
fi

# 8. Copy and set executable permission
cp -f "$EXTRACTED_BIN" "$TARGET_BIN"
chmod 755 "$TARGET_BIN"

success "Installed \${BOLD}\${APP_NAME}\${NC} to \${CYAN}\${TARGET_BIN}\${NC}"

# 9. Verify PATH
case ":\${PATH}:" in
  *:"\${INSTALL_DIR}":*)
    # In PATH
    ;;
  *)
    printf "\\n"
    warn "\${INSTALL_DIR} is not in your \\$PATH"
    printf "  Add it to your shell configuration:\\n"
    if [ -n "\${ZSH_VERSION:-}" ] || [ -f "\$HOME/.zshrc" ]; then
      printf "    \${DIM}echo 'export PATH=\\"%s:\\$PATH\\"' >> ~/.zshrc && source ~/.zshrc\${NC}\\n" "$INSTALL_DIR"
    else
      printf "    \${DIM}echo 'export PATH=\\"%s:\\$PATH\\"' >> ~/.bashrc && source ~/.bashrc\${NC}\\n" "$INSTALL_DIR"
    fi
    ;;
esac

# 10. Execute quick version check if available in PATH
if command -v "$APP_NAME" >/dev/null 2>&1; then
  VER_OUTPUT="$("$APP_NAME" --version 2>/dev/null || true)"
  if [ -n "$VER_OUTPUT" ]; then
    success "Verified \${BOLD}\${APP_NAME}\${NC} \${DIM}(\${VER_OUTPUT})\${NC}"
  fi
fi

printf "\\n\${GREEN}\${BOLD}  Ready to go!\${NC} Run '\${CYAN}\${APP_NAME} --help\${NC}' to get started.\\n\\n"
`;
}

export async function runInstallerCommand(options: InstallerCliOptions = {}): Promise<void> {
  const cwd = options.cwd || process.cwd();
  console.log(formatHeader("installer", "Generating standalone bash installer script"));

  const config = await resolveConfig(cwd);
  const outputPath = path.resolve(cwd, options.output || "install.sh");

  const content = generateInstallScript({
    appName: config.name,
    repo: options.repo,
    defaultDir: options.defaultDir,
  });

  fs.writeFileSync(outputPath, content, { encoding: "utf8", mode: 0o755 });

  const relOutput = path.relative(cwd, outputPath) || outputPath;
  console.log(`  ${symbols.success}  Generated ${pc.green(relOutput)}`);
  console.log(`\n  Usage Instructions:`);
  console.log(`    ${symbols.bullet} Users can install your CLI with a single command:`);
  const repoSlug = options.repo
    ? options.repo.replace(/^https?:\/\/github\.com\//, "").replace(/\.git$/, "")
    : `username/${config.name}`;
  console.log(`      ${pc.cyan(`curl -fsSL https://raw.githubusercontent.com/${repoSlug}/main/${relOutput} | bash`)}`);
  console.log(`\n    ${symbols.bullet} Or run locally:`);
  console.log(`      ${pc.cyan(`./${relOutput}`)}\n`);
}
